FROM node:22-alpine

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY --chown=node:node . .
RUN sed -i 's/\/sys\/class\/gpio/\/app\/fake_gpio/g' ./node_modules/node-web-gpio/dist/index.js

USER node
EXPOSE 3000

ENTRYPOINT ["npx", "tsx", "--inspect=0.0.0.0:9230", "--env-file=.env", "src/index"]
